zendesk:
  permission-group-title: "Agents and Managers"
#  locale                : "en-us"
  comments-disabled     : false
#  notify-subscribers    : true
  max-attempts          : 5
  forced-update         : true
  publish               : true

properties:
  template:
    category:
      title       : CATEGORY_TITLE
      oldTitle    : CATEGORY_OLD_TITLE
      description : CATEGORY_DESCRIPTION
      position    : CATEGORY_POSITION

    section:
      title       : SECTION_TITLE
      oldTitle    : SECTION_OLD_TITLE
      description : SECTION_DESCRIPTION
      position    : SECTION_POSITION

asciidoc:
  template:
    title     : ":ZENDESK-TITLE:"
    title-old : ":ZENDESK-OLD-TITLE:"
    position  : ":ZENDESK-ORDER:"
    tags      : ":ZENDESK-TAGS:"
    draft     : ":ZENDESK-DRAFT:"
    promoted  : ":ZENDESK-PROMOTED:"

server:
  port: 8088

spring:
  main:
    banner-mode: "off"
  profiles:
    active: main

logging:
  level:
    root: WARN
    org.zendesk: ${LOGLEVEL:INFO}
    com.dxfeed: ${LOGLEVEL:INFO}
