on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Build & Release

env:
  JARFILE: asciidoc2zendesk.jar
  ARTIFACT: asciidoc2zendesk-%VERSION%.tar.gz

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          echo ::set-env name=ARTIFACT::$(echo ${ARTIFACT} | sed "s/%VERSION%/$(echo ${GITHUB_REF:10})/g" )
          echo ::set-env name=JARFILE::$(echo ${JARFILE})
      - name: Build
        uses: ./.github/actions/build
        id: build-app
        with:
          jarfile:  ${{ env.JARFILE }}
          artifact: ${{ env.ARTIFACT }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT }}
          path: target/${{ env.ARTIFACT }}

  publish:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    name: publish release
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          echo ::set-env name=ARTIFACT::$(echo ${ARTIFACT} | sed "s/%VERSION%/$(echo ${GITHUB_REF:10})/g" )
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT }}
          path: downloads/
      - name: Publish release
        uses: ./.github/actions/publish
        with:
          args: downloads/
          draft_regex: '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+'
          prerelease_regex: '[a-zA-Z]+-[0-9]+.[0-9]+.[0-9]+'
        env:
          RELEASE_PREFIX: ${{ env.RELEASE_PREFIX }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
